### ISSUE TITLE
new version with new error: pipeline must have at least one non-pattern target.

### ISSUE THREAD

**Issue by yonicd** [wlandau/targets#245] opened 2020-12-14 15:02 UTC
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I was working on targets/tarchetypes:

```r
   tarchetypes * 0.0.0.9000 2020-11-10 [1] Github (wlandau/tarchetypes@80402af)
   targets     * 0.0.0.9002 2020-11-10 [1] Github (wlandau/targets@c7e6600)   
```

 and upgraded to current head https://github.com/wlandau/targets/commit/940949c4dbbb44033ff29ecf956af6d3459f10ed.

Using my same workflow i am getting this error when using `tar_visnetwork(targets_only = TRUE)`:

`pipeline must have at least one non-pattern target.`

<details closed>
<summary> <span title='Click to Expand'> last trace </span> </summary>

```r


 Stack trace:

 Process 29564:
 1. targets:::tar_visnetwork(targets_only = TRUE)
 2. targets:::callr_outer(targets_function = tar_visnetwork_inner,  ...
 3. targets:::trn(is.null(callr_function), callr_inner(target_script_path(),  ...
 4. base:::do.call(callr_function, prepare_callr_arguments(callr_function,  ...
 5. (function (func, args = list(), libpath = .libPaths(), repos = default_repos(),  ...
 6. callr:::get_result(output = out, options)
 7. throw(newerr, parent = remerr[[2]])

 x callr subprocess failed: pipeline must have at least one non-pattern target. 

 Process 9696:
 19. (function (targets_script, targets_function, targets_arguments)  ...
 20. base:::source(targets_script)
 21. base:::withVisible(eval(ei, envir))
 22. base:::eval(ei, envir)
 23. base:::eval(ei, envir)
 24. purrr::walk(pipelines_files, source)
 25. purrr:::map(.x, .f, ...)
 26. base:::.f(.x[[i]], ...)
 27. base:::withVisible(eval(ei, envir))
 28. base:::eval(ei, envir)
 29. base:::eval(ei, envir)
 30. targets:::tar_pipeline(tar_target(boot_frame, { ...
 31. targets:::pipeline_init(unlist(list(...), recursive = TRUE))
 32. targets:::pipeline_envir(targets)
 33. targets:::trn(length(names) > 0L, throw_validate("pipeline must have at least one non-pattern tar ...
 34. targets:::throw_validate("pipeline must have at least one non-pattern target.")
 35. base:::stop(condition_validate(...))
 36. (function (e)  ...

 x pipeline must have at least one non-pattern target. 


```

</details>
<br>

target

```r
library(targets)

tar_script({
library(tarchetypes)
stem <- 'PATH_TO_DATA'
adam_stem <- file.path(stem, 'adam')
sdtm_stem <- file.path(stem, 'sdtm')

adam_domains <- c('adcm','adsl') 
sdtm_domains <- c('lb')
adam_files <- file.path(adam_stem,glue::glue('{adam_domains}','sas7bdat',.sep = '.'))
sdtm_files <- file.path(sdtm_stem,glue::glue('{sdtm_domains}','sas7bdat',.sep = '.'))

pipe_data <- tar_pipeline(
  
  tar_map(values = tibble::tibble(
    domains = c(adam_domains,sdtm_domains),
    files = c(adam_files,sdtm_files)),
    names = 'domains',
    tar_target(file,files,format = 'file',deployment = "main"),
    tar_target(data, 
               haven::read_sas(file),
               format = "qs",
               deployment = "main")
  )
)
})

tar_visnetwork(targets_only = TRUE)
```

<details closed>
<summary> <span title='Click to Expand'> session info </span> </summary>

```r

- Session info -------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2020-12-14                  

- Packages -----------------------------------------------------------------------------------------
 ! package        * version    date       lib source                              
 P assertthat       0.2.1      2019-03-21 [?] CRAN (R 4.0.2)                      
   backports        1.2.0      2020-11-02 [1] CRAN (R 4.0.3)                      
 P binom            1.1-1      2014-01-02 [?] CRAN (R 4.0.3)                      
 P callr            3.4.3      2020-03-28 [?] CRAN (R 4.0.2)                      
 P cli              2.1.0      2020-10-12 [?] CRAN (R 4.0.3)                      
 P clipr            0.7.0      2019-07-23 [?] CRAN (R 4.0.2)                      
 P clustermq      * 0.8.95.1   2020-07-13 [?] CRAN (R 4.0.3)                      
 P codetools        0.2-16     2018-12-24 [?] CRAN (R 4.0.2)                      
 P colorspace       1.4-1      2019-03-18 [?] CRAN (R 4.0.2)                      
 P crayon           1.3.4      2017-09-16 [?] CRAN (R 4.0.2)                      
 P data.table       1.13.0     2020-07-24 [?] CRAN (R 4.0.2)                      
 P desc             1.2.0      2018-05-01 [?] CRAN (R 4.0.2)                      
 P details          0.2.1      2020-09-08 [?] local                               
   digest           0.6.27     2020-10-24 [1] CRAN (R 4.0.3)                      
 P distributional   0.2.1      2020-10-06 [?] CRAN (R 4.0.3)                      
 P dplyr            1.0.2      2020-08-18 [?] CRAN (R 4.0.2)                      
 P ellipsis         0.3.1      2020-05-15 [?] CRAN (R 4.0.2)                      
 P evaluate         0.14       2019-05-28 [?] CRAN (R 4.0.2)                      
 P fansi            0.4.1      2020-01-08 [?] CRAN (R 4.0.2)                      
 P farver           2.0.3      2020-01-16 [?] CRAN (R 4.0.2)                      
 P forcats          0.5.0      2020-03-01 [?] CRAN (R 4.0.2)                      
 P foreach          1.5.0      2020-03-30 [?] CRAN (R 4.0.2)                      
 P fs               1.5.0      2020-07-31 [?] CRAN (R 4.0.2)                      
 P generics         0.1.0      2020-10-31 [?] CRAN (R 4.0.3)                      
 P ggdist           2.3.0      2020-10-31 [?] CRAN (R 4.0.3)                      
 P ggplot2          3.3.2      2020-06-19 [?] CRAN (R 4.0.2)                      
 P glue             1.4.2      2020-08-27 [?] CRAN (R 4.0.2)                      
 P gridExtra        2.3        2017-09-09 [?] CRAN (R 4.0.2)                      
 P gtable           0.3.0      2019-03-25 [?] CRAN (R 4.0.2)                      
 P gtsummary        1.3.5      2020-09-29 [?] CRAN (R 4.0.2)                      
 P haven            2.3.1      2020-06-01 [?] CRAN (R 4.0.2)                      
 P here             0.1        2017-05-28 [?] CRAN (R 4.0.2)                      
 P hms              0.5.3      2020-01-08 [?] CRAN (R 4.0.2)                      
 P htmltools        0.5.0      2020-06-16 [?] CRAN (R 4.0.2)                      
 P htmlwidgets      1.5.1      2019-10-08 [?] CRAN (R 4.0.2)                      
 P httr             1.4.2      2020-07-20 [?] CRAN (R 4.0.2)                      
 P igraph           1.2.5      2020-03-19 [?] CRAN (R 4.0.2)                      
 P iterators        1.0.12     2019-07-26 [?] CRAN (R 4.0.2)                      
 P jsonlite         1.7.1      2020-09-07 [?] CRAN (R 4.0.2)                      
 P knitr            1.30       2020-09-22 [?] CRAN (R 4.0.3)                      
 P labelled         2.7.0      2020-09-21 [?] CRAN (R 4.0.3)                      
 P lifecycle        0.2.0      2020-03-06 [?] CRAN (R 4.0.2)                      
 P magrittr         1.5        2014-11-22 [?] CRAN (R 4.0.2)                      
 P munsell          0.5.0      2018-06-12 [?] CRAN (R 4.0.2)                      
 P pillar           1.4.6      2020-07-10 [?] CRAN (R 4.0.2)                      
 P pkgconfig        2.0.3      2019-09-22 [?] CRAN (R 4.0.2)                      
 P png              0.1-7      2013-12-03 [?] CRAN (R 4.0.0)                      
 P processx         3.4.3      2020-07-05 [?] CRAN (R 4.0.2)                      
 P ps               1.3.4      2020-08-11 [?] CRAN (R 4.0.2)                      
 P purrr            0.3.4      2020-04-17 [?] CRAN (R 4.0.2)                      
   R6               2.5.0      2020-10-28 [1] CRAN (R 4.0.3)                      
 P Rcpp             1.0.5      2020-07-06 [?] CRAN (R 4.0.2)                      
 P renv             0.12.2-13  2020-11-13 [?] Github (rstudio/renv@d022cac)       
   rlang            0.4.8      2020-10-08 [1] CRAN (R 4.0.3)                      
 P rmarkdown        2.5        2020-10-21 [?] CRAN (R 4.0.2)                      
 P rprojroot        1.3-2      2018-01-03 [?] CRAN (R 4.0.2)                      
 P rstudioapi       0.11       2020-02-07 [?] CRAN (R 4.0.2)                      
 P scales           1.1.1      2020-05-11 [?] CRAN (R 4.0.2)                      
 P sessioninfo      1.1.1      2018-11-05 [?] CRAN (R 4.0.2)                      
 P snakecase        0.11.0     2019-05-25 [?] CRAN (R 4.0.2)                      
 P stringi          1.4.6      2020-02-17 [?] CRAN (R 4.0.0)                      
 P stringr          1.4.0      2019-02-10 [?] CRAN (R 4.0.2)                      
 P tarchetypes    * 0.0.0.9001 2020-12-14 [?] Github (wlandau/tarchetypes@6af0095)
 P targets        * 0.0.0.9003 2020-12-14 [?] Github (wlandau/targets@940949c)    
 P tibble           3.0.4      2020-10-12 [?] CRAN (R 4.0.3)                      
 P tidyr            1.1.2      2020-08-27 [?] CRAN (R 4.0.2)                      
 P tidyselect       1.1.0      2020-05-11 [?] CRAN (R 4.0.2)                      
 P utf8             1.1.4      2018-05-24 [?] CRAN (R 4.0.2)                      
 P vctrs            0.3.4      2020-08-29 [?] CRAN (R 4.0.2)                      
 P vip              0.2.2      2020-04-06 [?] CRAN (R 4.0.2)                      
 P visNetwork       2.0.9      2019-12-06 [?] CRAN (R 4.0.2)                      
   withr            2.3.0      2020-09-22 [1] CRAN (R 4.0.2)                      
 P xfun             0.18       2020-09-29 [?] CRAN (R 4.0.3)                      
 P xml2             1.3.2      2020-04-23 [?] CRAN (R 4.0.2)                      
 P yaml             2.2.1      2020-02-01 [?] CRAN (R 4.0.2)                      

[1] C:/Users/jonathan.sidi/AppData/Local/Temp/Rtmpm4MXxx/renv-system-library

 P -- Loaded and on-disk path mismatch.

```

</details>
<br>

What trouble are you having?

## Reproducible example

* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Desired result

What output or behavior do you want to see? Please be as specific as you can.

## Diagnostic information

* A [reproducible example](https://github.com/tidyverse/reprex).
* Session info, available through `sessionInfo()` or [`reprex(si = TRUE)`](https://github.com/tidyverse/reprex).
* A stack trace from `traceback()` or `rlang::trace_back()`.
* The [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the GitHub commit of `targets` currently installed. `packageDescription("targets")$GithubSHA1` shows you this.

**Comment by wlandau** [comment] 2020-12-14 18:22
`targets` throws that error message if every single target in the pipeline uses dynamic branching (e.g. `tar_target(..., pattern = map(other_target))`). If you define any target without setting the `pattern` argument, then the error should go away. (Maybe you defined a lot of targets but not all of them made it into `tar_pipeline()` somehow?) Unfortunately, I cannot reproduce what you see if I create a reprex out of the code above.

``` r
library(targets)
tar_script({
  library(tarchetypes)
  tar_pipeline(
    tar_map(
      values = tibble::tibble(
        domains = c("domain1", "domain2"),
        files = c("file1.sas7bdat", "file2.sas7bdat")
      ),
      names = "domains",
      tar_target(file, files, format = "file", deployment = "main"),
      tar_target(
        data, 
        haven::read_sas(file),
        format = "qs",
        deployment = "main"
      )
    )
  )
})
tar_visnetwork()
```

![](https://i.imgur.com/gZ2rNfg.png)

<sup>Created on 2020-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment] 2020-12-14 18:24
And what version of R are you using?

**Comment by yonicd** [comment] 2020-12-14 20:36
thanks for the explanation. 

Is tar_map still thought of as dynamic branching? the example above and also the one you wrote do not use pattern at all in them.

> targets throws that error message if every single target in the pipeline uses dynamic branching (e.g. tar_target(..., pattern = map(other_target))).

thanks

**Comment by wlandau** [comment] 2020-12-14 20:39
tar_map() is static branching. Dynamic branching always makes use of pattern somehow, either explicitly in tar_target() or implicitly in some higher level functions like tar_rep(). Check tar_manifest() if you are unsure.

**Comment by yonicd** [comment] 2020-12-14 20:58
i see where me error is coming from. 

I have 3 pipelines that I am sourcing into `_targets.R`

```
library(targets)
library(tarchetypes)
library(clustermq)

options(
  tidyverse.quiet = TRUE,
  clustermq.scheduler = "multiprocess"
)


clustermq::register_dopar_cmq(n_jobs=7)

pipelines_path <- here::here('script/pipelines')
pipelines_files <- list.files(pipelines_path,pattern = 'R$',full.names = TRUE)

> pipelines_files
[1] "C:/trials/script/pipelines/data_assembly.R"
[2] "C:/trials/script/pipelines/diagnostics.R"  
[3] "C:/trials/script/pipelines/modeling.R"     
[4] "C:/trials/script/pipelines/reporting.R"

purrr::walk(pipelines_files,source)

pipe_model <- tar_bind(pipe_model_prep,pipe_logistic_model,pipe_rf_model)

targets::tar_bind(pipe_data,pipe_model,pipe_vpc)  #,pipe_report,pipe_model_report
```

`pipe_vpc` is a pipeline with only dynamic branching. 

I think when i sources there is a check to see that the pipeline is ok?

i thought that by putting all the pipelines in a `tar_bind` targets would see the other non dynamic parts of the binded pipeline.

here is a reprex (!)

``` r
library(targets)
tar_dir({
  tar_script({
    library(tarchetypes)
    
    pipe1 <- tar_pipeline(
      tar_target(domains,c("domain1", "domain2"))
    )
    
    pipe2 <- tar_pipeline(
      tar_target(domains2,sprintf('%s_2',domnains),pattern = map(domains))
    )
    
    pipe3 <- tar_pipeline(
      tar_map(
        values = tibble::tibble(
          domains = c("domain1", "domain2"),
          files = c("file1.sas7bdat", "file2.sas7bdat")
        ),
        names = "domains",
        tar_target(file, files, format = "file", deployment = "main"),
        tar_target(
          data,
          haven::read_sas(file),
          format = "qs",
          deployment = "main"
        )
      )
    )
    
    targets::tar_bind(pipe1,pipe2,pipe3)
  })

  tar_visnetwork()
})
#> Error : pipeline must have at least one non-pattern target.
#> Error: callr subprocess failed: pipeline must have at least one non-pattern target.
```

<sup>Created on 2020-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment] 2020-12-14 22:34
That's helpful, thanks. Should be fixed now.

**Closed** 2020-12-14 22:33 UTC
Labels: depends: reprex, status: cannot reproduce, type: trouble
