### ISSUE TITLE
Smarter checking of need to recompute downstream targets?

### ISSUE THREAD

**Issue by mike-lawrence** [wlandau/targets#205] opened 2020-10-28 14:27 UTC
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [ ] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

I think the current behaviour is for a target `z` to check if any of its upstream targets (ex. `y`) have had to be recomputed, and if so `z` will be recomputed too. However, in my workflow with dynamic targets I'll often find some branches where `z` throws an error and I find that I need to tweak what happens in `y` to fix things. In that case `y` is toggled to be recomputed and that's fine, but in cases where the edit to `y`'s operation only affects a small subset of its branches, `z` really doesn't need to be recomputed for most branches, just those that have changed in their output thanks to the new code for `y`. Since I think hashes of things are already being stored, would it be straightforward to, when checking `z`s branches, check the hashes of the latest data from `y` and only run `z`  for those branches where the `y` hash has changed?

If there's no side effects of this approach that I haven't considered and this is deemed something the project could use, I'd delve into the source to see if I can manage a PR for it.

**Comment by wlandau** [comment] 2020-10-28 15:32
Target invalidation is already hash-based. If the upstream targets were recomputed but returned the exact same data, downstream targets will not necessarily run. This applies to branches as well. If you are having trouble, it could be due to https://github.com/wlandau/targets/issues/200, which is now fixed. I suggest updating to the latest `targets`. The concept of cues is related, e.g. `tar_cue()`.

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_pipeline(
    tar_target(x, c(1L, 2L)),
    tar_target(y, x, pattern = map(x)),
    tar_target(z, y, pattern = map(y))
  )
})

tar_make()
#> ● run target x
#> ● run branch y_29239c8a
#> ● run branch y_7cc32924
#> ● run branch z_d0697b30
#> ● run branch z_959da4d3

# Change the return value of just one branch.
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_pipeline(
    tar_target(x, c(1L, 3L)),
    tar_target(y, x, pattern = map(x)),
    tar_target(z, y, pattern = map(y))
  )
})

tar_make()
#> ● run target x
#> ✓ skip branch y_29239c8a
#> ● run branch y_bd602d50
#> ✓ skip branch z_d0697b30
#> ● run branch z_92be5b5f

# Change the code but not the return values of y.
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_pipeline(
    tar_target(x, c(1L, 3L)),
    tar_target(y, x + 1L - 1L, pattern = map(x)),
    tar_target(z, y, pattern = map(y))
  )
})

tar_make()
#> ✓ skip target x
#> ● run branch y_29239c8a
#> ● run branch y_bd602d50
#> ✓ skip branch z_d0697b30
#> ✓ skip branch z_92be5b5f
```

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed by wlandau** 2020-10-28 15:32 UTC
Labels: type: new feature

**Comment by wlandau** [comment] 2020-10-28 15:34
Another example:

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_pipeline(
    tar_target(x, c(1, 2)),
    tar_target(y, x, pattern = map(x)),
    tar_target(z, y, pattern = map(y))
  )
})

tar_make()
#> ● run target x
#> ● run branch y_87b6379a
#> ● run branch y_d6660f34
#> ● run branch z_3dbedc64
#> ● run branch z_4cf4662b

# Change the code but only one branch of y returned a different value.
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_pipeline(
    tar_target(x, c(1, 2)),
    tar_target(y, sqrt(x), pattern = map(x)),
    tar_target(z, y, pattern = map(y))
  )
})

tar_make()
#> ✓ skip target x
#> ● run branch y_87b6379a
#> ● run branch y_d6660f34
#> ✓ skip branch z_3dbedc64
#> ● run branch z_4cf4662b
```

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mike-lawrence** [comment] 2020-10-28 15:43
Amazing, thanks! I also just realized that my scheme for appending metadata to chunks of data in my pipeline is was changing the hash of the targets. Worked out a smarter scheme that avoids that and back to the expected behaviour. Sorry for the false alarm!

**Comment by mike-lawrence** [comment] 2020-10-29 19:14
One Q: unless I'm doing something else wrong (entirely possible), it seems that target branches get individually checked for updates. If a pipeline has a lot of branches per target and only later targets need to be re-run, the checking of earlier targets can take up a lot of time. I wonder if there's a way around this. Maybe if the individual branch hashes are in turn hashed together and stored with the parent entry, downstream targets can check if this hash has changed, and only if so bother going on to check individual branches?

**Comment by wlandau** [comment] 2020-10-29 19:56
Branches inevitably get checked one at a time. In `drake` I initially tried some shortcuts, but they always led to incorrect invalidation decisions, so I backed off.

Of all the potential performance issues, overhead with many targets is the problem I have spent the most time and effort addressing (profiling studies [here](https://github.com/wlandau/targets/blob/main/tests/performance/test-maps.R) and [here](https://github.com/wlandau/targets/blob/main/tests/performance/test-stems.R)). I can no longer reduce overhead for those use cases, but if you experience slowness, feel free to post a reproducible example and I will profile it with [`proffer`](https://github.com/r-prof/proffer).

The number of targets/branches is entirely within the user's control. A target should be small enough to not invalidate the whole pipeline but large enough to take a decent bite out of the runtime. A common mistake is to create tens of thousands of targets that each run in a matter of seconds. If you start to run into a situation like this, I recommend batching the computation into a smaller number of heavier targets as [described here](https://wlandau.github.io/targets-manual/dynamic.html#batching). See also [`tarchetypes::tar_rep()`](https://wlandau.github.io/tarchetypes/reference/tar_rep.html).
